### ISSUE TITLE
Iterative Depth/Breadth-first tree traversals

### ISSUE THREAD

**Issue by reubenrowe** [RHUL-CS-Projects/graphfellow#24]
For CS1812, it would be great to have animations of the iterative algorithms for doing depth- and breadth-first traversals for trees, using stacks and queues, respectively.

**Comment by davewhiteland** [comment]
Implemented by
https://cs.rhul.ac.uk/home/teas024/graphs/trees/
(from that some general graph-interaction stuff (CSS, common JS) may emerge but that's the tree traversal done for now :-) )
